### ISSUE TITLE
Como puedo probar el programa

### ISSUE THREAD

**Issue by abenitez74** [victoradrianjimenez/sistema-encuestas#1]
Quisiera saber como puedo ver funcionando el software, tengo instalado xammp y ejecute los scripts requeridos. Muchas gracias

**Comment by victoradrianjimenez** [comment]
Hola abenitez74. Te comento que este proyecto está abandonado desde 2013. De todas maneras me puse a ver el error y lo corregí. Desde que se inició el proyecto pasaron muchas versiones de PHP, y por eso surgió un error en uno de los archivos del framework utilizado. Puse una copia funcional en "http://sistema-encuestas-unt.herokuapp.com" (usuario: admin, contraseña: password). No puedo dar garantías de que funcione al 100% en nuevas versiones de PHP (aunque lo probé y funciona perfectamente). Siempre que los errores sean fáciles de corregir, puedo destinarle tiempo. Saludos y perdón por tardar en responder los issues.
